import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase : new URL("https://hitesh-padhara.vercel.app"),
  keywords:["hiteshpadhara", "hitesh padhara", "freelancer", "upwork", "Full Stack Developer", "laravel","Laravel","PHP","go","Go developer"],
  title: {
    default:"HiteshPadhara",
    template:`%s | Hitesh Padhara`
  },
  description: "Generated by Hitesh Padhara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} data-theme="dark">{children}</body>
    </html>
  );
}